apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  namespace: go-app
  labels:
    app: go-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: app
        image: go-server:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_PASSWORD
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: JWT_SECRET
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: PORT
        ports:
        - containerPort: 8080