apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: sirius
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USER: dbuser
  DB_PASS: dbpass
  DB_NAME: exam
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: sirius
type: Opaque
stringData:
  S3_HOST: minio
  S3_PORT: "9000"
  S3_USER: s3user
  S3_PASS: s3pass123
  MINIO_ROOT_USER: s3user
  MINIO_ROOT_PASSWORD: s3pass123
